set(_CATKIN_CURRENT_PACKAGE "cartographer_turtlebot")
set(cartographer_turtlebot_VERSION "0.3.0")
set(cartographer_turtlebot_MAINTAINER "The Cartographer Authors <google-cartographer@googlegroups.com>")
set(cartographer_turtlebot_PACKAGE_FORMAT "2")
set(cartographer_turtlebot_BUILD_DEPENDS "g++-static" "cartographer_ros" "depthimage_to_laserscan" "kobuki" "kobuki_core" "message_runtime" "openni2_launch" "roscpp" "roslib" "sensor_msgs" "turtlebot_bringup" "urg_node")
set(cartographer_turtlebot_BUILD_EXPORT_DEPENDS "cartographer_ros" "depthimage_to_laserscan" "kobuki" "kobuki_core" "message_runtime" "openni2_launch" "roscpp" "roslib" "sensor_msgs" "turtlebot_bringup" "urg_node")
set(cartographer_turtlebot_BUILDTOOL_DEPENDS "catkin")
set(cartographer_turtlebot_BUILDTOOL_EXPORT_DEPENDS )
set(cartographer_turtlebot_EXEC_DEPENDS "cartographer_ros" "depthimage_to_laserscan" "kobuki" "kobuki_core" "message_runtime" "openni2_launch" "roscpp" "roslib" "sensor_msgs" "turtlebot_bringup" "urg_node")
set(cartographer_turtlebot_RUN_DEPENDS "cartographer_ros" "depthimage_to_laserscan" "kobuki" "kobuki_core" "message_runtime" "openni2_launch" "roscpp" "roslib" "sensor_msgs" "turtlebot_bringup" "urg_node")
set(cartographer_turtlebot_TEST_DEPENDS "rosunit")
set(cartographer_turtlebot_DOC_DEPENDS )
set(cartographer_turtlebot_URL_WEBSITE "https://github.com/googlecartographer/cartographer_turtlebot")
set(cartographer_turtlebot_URL_BUGTRACKER "")
set(cartographer_turtlebot_URL_REPOSITORY "")
set(cartographer_turtlebot_DEPRECATED "")